### ISSUE TITLE
Negative curvature makes rover go backwards

### ISSUE THREAD

**Issue by duncanrhamill** [SUSF-Robotics-and-Software/phobos_sw#20]
A somewhat serious bug here, but negative curvatures make the rover drive backwards. Probably a bug in `loco_ctrl::calc_ackerman_generic`.

**Comment by EthanTreg** [comment]
Commit 442f718
Fixed negative curvature bug.
Inputting negative curvature caused the rover to drive backwards.
Fix was to add absolute to curvature in speed calculation.
