### ISSUE TITLE
Point turn directions wrong

### ISSUE THREAD

**Issue by duncanrhamill** [SUSF-Robotics-and-Software/phobos_sw#24]
I think the directions of point turns are wrong, I've observed this using `auto mnvr pt`.

**Comment by EthanTreg** [comment]
da3a460

Fixed point turn incorrect rotation direction.

The wheels on the right side of the rover were inverted rather than the left side.

**Comment by EthanTreg** [comment]
Accidently submitted both changes to Ackermann and point turn. Ackermann is still a work in progress and wasn't meant to be pushed with the update to point turn. Not sure how to remove the Ackermann changes.
